apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels:
    app: public-webservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: my-wordpress
